#!/bin/bash

# Activation de la coloration syntaxique et du fond noir pour vim
/bin/sed -i 's/^"syntax on/syntax on/' /etc/vim/vimrc
/bin/sed -i 's/^"set background=dark/set background=dark/' /etc/vim/vimrc
/bin/echo 'colorscheme solarized' >> /etc/vim/vimrc

# Remplacement du Bach.Bachrc
/bin/mv -f /etc/bash.bashrc /etc/bash.bashrc.hold
/bin/cp -f /etc/fdh-bash.bashrc /etc/bash.bashrc

# Nettoyage du /etc/skel (pour les utilisateurs futurs)
/bin/rm -f /etc/skel/.bashrc
/bin/rm -f /etc/skel/.bash_logout

# Nettoyage du /root
/bin/rm -f /root/.bashrc
/bin/rm -f /root/.bash_logout

# Nettoyage de "homedir"
for USER in `/bin/ls /home`
do
	/bin/rm -f /home/$USER/.bashrc
	/bin/rm -f /home/$USER/.bash_logout
	/bin/cp /etc/skel/.inputrc /home/$USER/
	/bin/chown $USER:$USER /home/$USER/.inputrc
	/bin/cp /etc/skel/.gitconfig /home/$USER/
	/bin/chown $USER:$USER /home/$USER/.gitconfig
done
